default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: blog_rails_api
  username: postgres
  password: 
test:
  <<: *default
  database: blog_rails_api_test
production:
  <<: *default
  database: blog_rails_api_prod
  username: blog_rails_api
  password: <%= ENV['SYNONYMS_01_API_DATABASE_PASSWORD'] %>
